spring:
  config:
    import: "classpath:secrets.properties"
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
  data:
    mongodb:
      database: telegram
      auto-index-creation: true
      uri: ${MONGO_URI}
telegram:
  bots:
    myBot:
      username: ${TG_USERNAME}
      token: ${TG_TOKEN}